

export const blogitems = [
    {
        id: 1,
        name: "How we can take care of our health against Virus",
        description: "Visitors will be able to choose to stay in one of two homes – part of a stacked building – or in a single dwelling, connected via a covered footbridge. Pitched roofs cover the trio of residencies, all of which feature folding full-length windows and balconies that let inhabitants gaze out across the boulder-covered surrounding region.",
        description2: "Visitors will be able to choose to stay in one of two homes – part of a stacked building – or in a single dwelling, connected via a covered footbridge. Pitched roofs cover the trio of residencies, all of which feature folding full-length windows and balconies that let inhabitants gaze out across the boulder-covered surrounding region.",
        description3: "Podcasting operational change management workflows to establish framework Taking seamless key formance indicators offline to maximise the long tail keep eye on the performing a deep dive on the start-up mentality collaborative admin empowered markets networks optimization",
        blockquote: "Creativity is just connecting things. When you ask creative people how they did something, they feel a little guilty because they didn't really do it, they just saw something. It seemed obvious to them after a while. That's because they were able to connect experiences they've had and synthesize new things.",
        blockquoteName: "- Mr. Dev",
        blockquoteSkills: "Founder of Apple Inc.",
        img: "images/img1.jpg",
        time: "4 min read",
        author: "TechyDevs",
        authorurl: "https://techydevs.com",
        date: "Jan 9, 2019",
        featured: true,
        bestFeatured: true,
        doctordetails: true,
        recentPost: true,
        tags: [
            "Coronavirus",
            "Clinic",
            "COVID-19",
        ]
    },
    {
        id: 2,
        name: "10 Ways to Stay Healthy on a Road Trip",
        description: "Visitors will be able to choose to stay in one of two homes – part of a stacked building – or in a single dwelling, connected via a covered footbridge. Pitched roofs cover the trio of residencies, all of which feature folding full-length windows and balconies that let inhabitants gaze out across the boulder-covered surrounding region.",
        description2: "Visitors will be able to choose to stay in one of two homes – part of a stacked building – or in a single dwelling, connected via a covered footbridge. Pitched roofs cover the trio of residencies, all of which feature folding full-length windows and balconies that let inhabitants gaze out across the boulder-covered surrounding region.",
        description3: "Podcasting operational change management workflows to establish framework Taking seamless key formance indicators offline to maximise the long tail keep eye on the performing a deep dive on the start-up mentality collaborative admin empowered markets networks optimization",
        blockquote: "Creativity is just connecting things. When you ask creative people how they did something, they feel a little guilty because they didn't really do it, they just saw something. It seemed obvious to them after a while. That's because they were able to connect experiences they've had and synthesize new things.",
        blockquoteName: "- Steve Jobs",
        blockquoteSkills: "Founder of Apple Inc.",
        img: "images/img2.jpg",
        time: "4 min read",
        author: "TechyDevs",
        authorurl: "https://techydevs.com",
        date: "Jan 8, 2019",
        featured: true,
        bestNews: true,
        doctordetails: true,
        recentPost: true,
        tags: [
            "Coronavirus",
            "Virus",
            "Medicine",
            "COVID-19",
        ]
    },
    {
        id: 3,
        name: "How Scientific Is Modern Medicine Really?",
        description: "Visitors will be able to choose to stay in one of two homes – part of a stacked building – or in a single dwelling, connected via a covered footbridge. Pitched roofs cover the trio of residencies, all of which feature folding full-length windows and balconies that let inhabitants gaze out across the boulder-covered surrounding region.",
        description2: "Visitors will be able to choose to stay in one of two homes – part of a stacked building – or in a single dwelling, connected via a covered footbridge. Pitched roofs cover the trio of residencies, all of which feature folding full-length windows and balconies that let inhabitants gaze out across the boulder-covered surrounding region.",
        description3: "Podcasting operational change management workflows to establish framework Taking seamless key formance indicators offline to maximise the long tail keep eye on the performing a deep dive on the start-up mentality collaborative admin empowered markets networks optimization",
        blockquote: "Creativity is just connecting things. When you ask creative people how they did something, they feel a little guilty because they didn't really do it, they just saw something. It seemed obvious to them after a while. That's because they were able to connect experiences they've had and synthesize new things.",
        blockquoteName: "- Jane Joe",
        blockquoteSkills: "Founder of Apple Inc.",
        img: "images/img3.jpg",
        time: "6 min read",
        author: "TechyDevs",
        authorurl: "https://techydevs.com",
        date: "Jan 11, 2019",
        featured: true,
        bestNews: true,
        recentPost: true,
        tags: [
            "Corona",
            "Clinic",
            "COVID-19",
        ]
    },
    {
        id: 4,
        name: "How we can take care of our health against Virus",
        description: "Visitors will be able to choose to stay in one of two homes – part of a stacked building – or in a single dwelling, connected via a covered footbridge. Pitched roofs cover the trio of residencies, all of which feature folding full-length windows and balconies that let inhabitants gaze out across the boulder-covered surrounding region.",
        description2: "Visitors will be able to choose to stay in one of two homes – part of a stacked building – or in a single dwelling, connected via a covered footbridge. Pitched roofs cover the trio of residencies, all of which feature folding full-length windows and balconies that let inhabitants gaze out across the boulder-covered surrounding region.",
        description3: "Podcasting operational change management workflows to establish framework Taking seamless key formance indicators offline to maximise the long tail keep eye on the performing a deep dive on the start-up mentality collaborative admin empowered markets networks optimization",
        blockquote: "Creativity is just connecting things. When you ask creative people how they did something, they feel a little guilty because they didn't really do it, they just saw something. It seemed obvious to them after a while. That's because they were able to connect experiences they've had and synthesize new things.",
        blockquoteName: "- John Jobs",
        blockquoteSkills: "Founder of Apple Inc.",
        img: "images/img1.jpg",
        time: "10 min read",
        author: "TechyDevs",
        authorurl: "https://techydevs.com",
        date: "Jan 12, 2019",
        bestNews: true,
        recentPost: true,
        tags: [
            "Hospital",
            "Corona",
            "Pharmacy",
            "COVID-19",
        ]
    },
    {
        id: 5,
        name: "10 Ways to Stay Healthy on a Road Trip",
        description: "Visitors will be able to choose to stay in one of two homes – part of a stacked building – or in a single dwelling, connected via a covered footbridge. Pitched roofs cover the trio of residencies, all of which feature folding full-length windows and balconies that let inhabitants gaze out across the boulder-covered surrounding region.",
        description2: "Visitors will be able to choose to stay in one of two homes – part of a stacked building – or in a single dwelling, connected via a covered footbridge. Pitched roofs cover the trio of residencies, all of which feature folding full-length windows and balconies that let inhabitants gaze out across the boulder-covered surrounding region.",
        description3: "Podcasting operational change management workflows to establish framework Taking seamless key formance indicators offline to maximise the long tail keep eye on the performing a deep dive on the start-up mentality collaborative admin empowered markets networks optimization",
        blockquote: "Creativity is just connecting things. When you ask creative people how they did something, they feel a little guilty because they didn't really do it, they just saw something. It seemed obvious to them after a while. That's because they were able to connect experiences they've had and synthesize new things.",
        blockquoteName: "- Petter Doe",
        blockquoteSkills: "Founder of Apple Inc.",
        img: "images/img2.jpg",
        time: "10 min read",
        author: "TechyDevs",
        authorurl: "https://techydevs.com",
        date: "Jan 14, 2019",
        tags: [
            "Coronavirus",
            "Prevention",
        ]
    },
    {
        id: 6,
        name: "How Scientific Is Modern Medicine Really?",
        description: "Visitors will be able to choose to stay in one of two homes – part of a stacked building – or in a single dwelling, connected via a covered footbridge. Pitched roofs cover the trio of residencies, all of which feature folding full-length windows and balconies that let inhabitants gaze out across the boulder-covered surrounding region.",
        description2: "Visitors will be able to choose to stay in one of two homes – part of a stacked building – or in a single dwelling, connected via a covered footbridge. Pitched roofs cover the trio of residencies, all of which feature folding full-length windows and balconies that let inhabitants gaze out across the boulder-covered surrounding region.",
        description3: "Podcasting operational change management workflows to establish framework Taking seamless key formance indicators offline to maximise the long tail keep eye on the performing a deep dive on the start-up mentality collaborative admin empowered markets networks optimization",
        blockquote: "Creativity is just connecting things. When you ask creative people how they did something, they feel a little guilty because they didn't really do it, they just saw something. It seemed obvious to them after a while. That's because they were able to connect experiences they've had and synthesize new things.",
        blockquoteName: "- Mark Jobs",
        blockquoteSkills: "Founder of Apple Inc.",
        img: "images/img3.jpg",
        time: "18 min read",
        author: "TechyDevs",
        authorurl: "https://techydevs.com",
        date: "Jan 17, 2019",
        tags: [
            "Coronavirus",
            "Clinic",
            "COVID-19",
        ]
    }
]

export const detailBlog = {
    id: 1,
    name: "How we can take care of our health against Virus",
    description: "Visitors will be able to choose to stay in one of two homes – part of a stacked building – or in a single dwelling, connected via a covered footbridge. Pitched roofs cover the trio of residencies, all of which feature folding full-length windows and balconies that let inhabitants gaze out across the boulder-covered surrounding region.",
    description2: "Visitors will be able to choose to stay in one of two homes – part of a stacked building – or in a single dwelling, connected via a covered footbridge. Pitched roofs cover the trio of residencies, all of which feature folding full-length windows and balconies that let inhabitants gaze out across the boulder-covered surrounding region.",
    description3: "Podcasting operational change management workflows to establish framework Taking seamless key formance indicators offline to maximise the long tail keep eye on the performing a deep dive on the start-up mentality collaborative admin empowered markets networks optimization",
    blockquote: "Creativity is just connecting things. When you ask creative people how they did something, they feel a little guilty because they didn't really do it, they just saw something. It seemed obvious to them after a while. That's because they were able to connect experiences they've had and synthesize new things.",
    blockquoteName: "- Steve Jobs",
    blockquoteSkills: "Founder of Apple Inc.",
    img: "images/img1.jpg",
    time: "4 min read",
    author: "TechyDevs",
    authorurl: "https://techydevs.com",
    date: "Jan 9, 2019",
    tags: [
        "Coronavirus",
        "Clinic",
        "Prevention",
        "Medicine",
        "Virus",
    ]
}